[app]
address = ":5000"

[db]
#driver = "mysql"
#connect = "root:@tcp(localhost:3306)/nlan?charset=utf8"
driver = "sqlite3"
connect = "./data/nlan.db"

[host]
address = "localhost"
from = 5001
to = 6000
